[main]
include=/usr/share/foot/themes/kitty
# font=mono:size=12
font = JetBrainsMono Nerd Font:size=12
initial-window-mode = maximized
[key-bindings]
fullscreen=F11
# foot.ini
# The default palette of xterm.

